logging:
  level:
    com.dengry.springbootshiro: debug #分包配置级别，即不同的目录下可以使用不同的级别
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbs?serverTimezone=UTC
    username: root
    password: 123
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  profiles:
    include: shiro